project:
  type: website
  output-dir: docs

website:
  title: "PharmaSUG China 2024 Pre-conference Training"
  description: "Good Software Engineering Practice with R"
  site-url: https://pharmarug.github.io/pharmasug2024-r-workshop/
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: "house-fill"
      - href: listing.qmd
        text: Slides
        icon: "file-earmark-slides"
  page-footer:
    center:
      - text: "PharmaSUG 2024"
        href: https://www.pharmasug-china.org/
      - text: "Source Code on GitHub"
        href: https://github.com/pharmarug/pharmasug2024-r-workshop

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true

editor: source
